[package]
name = "guess-a-number"
version = "0.1.0"
edition = "2021"
description = "Simple guess a number game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.0"
